@url_dev=http://localhost:3055/v1/api/


### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: b6bae8e81c8f635370ab80d08f3991a71ec5b685318b3dfaedb176bf54adc19878b8b4ceb66271195f36f9c283c51a9c1bb97101b61a4f1beda6aa998ea34dbd

{
    "name": "Shop TOPSJS7",
    "email": "shoptipjs7@gmail.com",
    "password": "123"


}